[workspace]
members = ["brownie", "database", "types"]
resolver = "2"

[workspace.dependencies]
strum = { version = "0.26", features = ["derive"] }
rand = "0.8.5"
poise = { git = "https://github.com/serenity-rs/poise", branch = "current" }
