[package]
name = "types"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["rt-multi-thread"] }
Inflector = "0.11.4"
itertools = "0.13.0"
poise.workspace = true
rand.workspace = true
